"""
Page 5 — RAG (Retrieval-Augmented Generation)
Question → retrieve relevant reviews → LLM answer.
"""
import streamlit as st
import pandas as pd
from pathlib import Path
import numpy as np
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(page_title="RAG", page_icon="🤖", layout="wide")
st.title("🤖 RAG — Retrieval-Augmented Generation")
st.markdown("Ask a question about insurance reviews. The system retrieves relevant reviews and generates an answer.")

OUTPUTS_DIR = Path("outputs")

@st.cache_data
def load_data():
    path = OUTPUTS_DIR / 'reviews_clean.csv'
    if path.exists():
        return pd.read_csv(path)
    return pd.DataFrame()

df = load_data()

if len(df) == 0:
    st.error("Data not found. Run Notebook 01 first.")
    st.stop()

# Sidebar settings
st.sidebar.header("RAG Settings")
n_retrieve = st.sidebar.slider("Reviews to retrieve", 3, 15, 5)
use_semantic = st.sidebar.checkbox("Use semantic search (FAISS)", value=True)

FAISS_PATH = OUTPUTS_DIR / 'faiss_index.bin'
EMBEDDINGS_PATH = OUTPUTS_DIR / 'sentence_embeddings.npy'
FAISS_AVAILABLE = FAISS_PATH.exists() and EMBEDDINGS_PATH.exists()

if use_semantic and not FAISS_AVAILABLE:
    st.sidebar.warning("FAISS not available. Using keyword search.")
    use_semantic = False

question = st.text_input(
    "Your question",
    placeholder="e.g. What do customers say about claims processing? Which insurer has the best service?"
)

if st.button("🔍 Ask", type="primary") and question.strip():

    # Step 1: Retrieve relevant reviews
    st.subheader("📚 Retrieved Reviews")

    if use_semantic and FAISS_AVAILABLE:
        import faiss
        from sentence_transformers import SentenceTransformer

        @st.cache_resource
        def load_retrieval():
            index = faiss.read_index(str(FAISS_PATH))
            st_model = SentenceTransformer('all-MiniLM-L6-v2')
            return index, st_model

        with st.spinner("Retrieving with semantic search..."):
            index, st_model = load_retrieval()
            q_emb = st_model.encode([question]).astype(np.float32)
            distances, indices = index.search(q_emb, n_retrieve)

        retrieved = []
        for dist, idx in zip(distances[0], indices[0]):
            if idx < len(df):
                row = df.iloc[idx]
                retrieved.append({
                    'text': row.get('text', ''),
                    'sentiment': row.get('sentiment', ''),
                    'star_rating': row.get('star_rating', ''),
                    'category': row.get('category', ''),
                    'assureur': row.get('assureur', ''),
                    'distance': round(float(dist), 4)
                })
    else:
        # Keyword-based retrieval
        keywords = [w.lower() for w in question.split() if len(w) > 3]
        mask = pd.Series([False] * len(df))
        for kw in keywords:
            mask = mask | df['text'].str.lower().str.contains(kw, na=False)
        retrieved_df = df[mask].head(n_retrieve)
        retrieved = retrieved_df[['text', 'sentiment', 'star_rating', 'category', 'assureur']].to_dict('records')

    if not retrieved:
        st.warning("No relevant reviews found.")
        st.stop()

    for i, rev in enumerate(retrieved):
        with st.expander(f"Review {i+1} | {rev.get('sentiment','?')} | ⭐{rev.get('star_rating','?')} | {rev.get('assureur','?')}"):
            st.write(rev.get('text', ''))

    # Step 2: Generate answer
    st.subheader("💬 Generated Answer")

    context = "\n".join([f"- [{r.get('sentiment','?')} / ⭐{r.get('star_rating','?')}] {r.get('text','')[:200]}"
                          for r in retrieved])

    # Try Ollama first, fallback to extractive summary
    def check_ollama():
        try:
            import requests
            r = requests.get("http://localhost:11434/api/tags", timeout=2)
            return r.status_code == 200
        except Exception:
            return False

    if check_ollama():
        import requests

        prompt = f"""You are an expert on insurance customer reviews. Answer the following question based on the provided review excerpts.

Question: {question}

Review excerpts:
{context}

Provide a concise, insightful answer based only on the reviews above. Mention specific patterns you observe."""

        with st.spinner("Generating answer with Ollama..."):
            response = requests.post(
                "http://localhost:11434/api/generate",
                json={"model": "llama3.2", "prompt": prompt, "stream": False},
                timeout=60
            )
            answer = response.json().get('response', 'No response received.')

        st.success(answer)
        st.caption("Generated by Ollama (llama3.2)")
    else:
        # Extractive summary fallback
        sentiments = [r.get('sentiment', '') for r in retrieved]
        avg_rating = sum([r.get('star_rating', 3) for r in retrieved]) / len(retrieved)

        pos_count = sentiments.count('positive')
        neg_count = sentiments.count('negative')
        neu_count = sentiments.count('neutral')

        summary = f"""Based on {len(retrieved)} retrieved reviews:

- **Average rating**: {avg_rating:.1f} ⭐
- **Sentiment breakdown**: {pos_count} positive, {neu_count} neutral, {neg_count} negative

**Key excerpts**:
{chr(10).join([f'• "{r["text"][:150]}..."' for r in retrieved[:3]])}

*Note: For AI-generated answers, install and run Ollama with llama3.2.*"""

        st.info(summary)
